#!/bin/sh
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
xsetroot -cursor_name left_ptr &
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            0
bspc config window_gap              0
bspc config automatic_scheme        alternate
bspc config split_ratio             0.5
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config pointer_motion_interval 7

bspc rule -a feh                                  state=floating
bspc rule -a mpv                                  state=floating
bspc rule -a Org.gnome.Nautilus:org.gnome.Nautilus state=floating
bspc rule -a Wpg                                  state=floating

$HOME/.config/polybar/launch.sh
