#! /bin/sh

xsetroot -cursor_name left_ptr &
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           5
bspc config automatic_scheme     alternate
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Wpg state=floating
